// This file was generated by the 'generate' command. Do not edit.
// CLDR version: 44

package locale

import (
	"reflect"
	"testing"
	"unicode/utf8"
)

type numberFormatData struct {
	symbols       Symbols
	posAffixes    Affixes
	negAffixes    Affixes
	minIntDigits  int
	minFracDigits int
	maxFracDigits int
	intGrouping   Grouping
	fracGrouping  Grouping
}

func TestLookupNumberFormat(t *testing.T) {
	// decimal formats
	testNumberFormatLookup(t, DecimalFormat, map[Locale]numberFormatData{
		0x0071: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x00c6: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 3}, Grouping{0, 0}},
		0x00f3: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x01c7: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x01d8: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x0243: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x0244: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x0248: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x024a: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x0287: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x02db: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x02e2: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x0392: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x0395: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 3}, Grouping{0, 0}},
		0x0396: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 3}, Grouping{0, 0}},
		0x0397: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
		0x03ac: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{2, 2}, Grouping{0, 0}},
		0x03c5: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 3}, Grouping{0, 0}},
		0x03ed: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 0, 3, Grouping{3, 2}, Grouping{0, 0}},
	})

	// money formats
	testNumberFormatLookup(t, MoneyFormat, map[Locale]numberFormatData{
		0x0001: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0005: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0007: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x000a: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x000c: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x000e: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0010: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0016: {Symbols{".", ",", "‎%‎", "‎-", "∞", "ليس رقمًا", '0'}, Affixes{"‏", " ¤"}, Affixes{"‏-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0035: {Symbols{".", ",", "%", "-", "∞", "NaN", '০'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0037: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0039: {Symbols{",", ".", "%", "-", "∞", "ND", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x003b: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0040: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x004b: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x004d: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x004f: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0053: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0055: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0061: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"¤ -", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0065: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0067: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x006b: {Symbols{".", ",", "%", "-", "∞", "NaN", '০'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x006f: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0071: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x0073: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0074: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x007a: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x007c: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0088: {Symbols{".", ",", "%", "-", "∞", "Терхьаш дац", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x008a: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x008c: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0090: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0097: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0099: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x009d: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x009f: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00a1: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00a3: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00a6: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00a8: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00a9: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00ab: {Symbols{".", "’", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"¤-", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00ae: {Symbols{".", "’", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00b0: {Symbols{".", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00b2: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00b4: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00b6: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00ba: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00be: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00c0: {Symbols{".", ",", "%", "-", "∞", "mnn", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00c3: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00c6: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00c8: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00cd: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00d8: {Symbols{".", "’", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"¤-", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x00f3: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x0105: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x010b: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"¤ -", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0136: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0138: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0139: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x013a: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x013e: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"¤-", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x013f: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0144: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"¤-", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0146: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x014d: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0150: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"¤ -", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0153: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0154: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"¤-", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0155: {Symbols{",", " ", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0157: {Symbols{",", ".", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0159: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x015b: {Symbols{"٫", "٬", "٪", "‎−", "∞", "ناعدد", '۰'}, Affixes{"‎¤", ""}, Affixes{"-‎¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x015c: {Symbols{"٫", "٬", "٪", "‎−", "∞", "ناعدد", '۰'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x015e: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0179: {Symbols{",", " ", "%", "−", "∞", "epäluku", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x017b: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x017d: {Symbols{",", ".", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0180: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01b3: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01b5: {Symbols{".", ",", "%", "-", "∞", "Nuimh", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01ba: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01bf: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01c3: {Symbols{".", "’", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01c7: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x01c9: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01cb: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01d4: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01d6: {Symbols{".", ",", "%", "‎-", "∞", "NaN", '0'}, Affixes{"‏", " ‏¤"}, Affixes{"‏-", " ‏¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01d8: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x01df: {Symbols{",", ".", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01e2: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01e4: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01e6: {Symbols{",", " ", "%", "-", "∞", "ՈչԹ", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01ea: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01ec: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"¤ -", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01ee: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01f4: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01f6: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01f7: {Symbols{".", "’", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"¤-", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x01ff: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0205: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0209: {Symbols{",", " ", "%", "-", "∞", "არ არის რიცხვი", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x020b: {Symbols{",", " ", "%", "-", "∞", "MdM", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x020f: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0213: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0215: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x021b: {Symbols{".", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x021d: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x021f: {Symbols{",", " ", "%", "-", "∞", "сан емес", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0223: {Symbols{",", ".", "%", "−", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"¤-", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0225: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0227: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0229: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x022b: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0239: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x023b: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x023d: {Symbols{",", " ", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x023f: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0241: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0243: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x0244: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x0248: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x024a: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x024c: {Symbols{",", " ", "%", "-", "∞", "сан эмес", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0252: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0254: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0256: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x025c: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0261: {Symbols{",", ".", "%", "-", "∞", "ບໍ່​ແມ່ນ​ໂຕ​ເລກ", '0'}, Affixes{"¤ ", ""}, Affixes{"¤ -", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0266: {Symbols{",", " ", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0268: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x026a: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x026c: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"¤- ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x026e: {Symbols{",", " ", "%", "-", "∞", "NS", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0272: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0277: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0285: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0287: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x028d: {Symbols{",", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0297: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0298: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x029c: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x029d: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x029f: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02a1: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02ab: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02b0: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02b2: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02b8: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"¤ -", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02c0: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02c6: {Symbols{",", " ", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02c9: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02cd: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02d3: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02d5: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", "¤"}, Affixes{"-", "¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02d8: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02db: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02e2: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x02ea: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02ee: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02f0: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x02ff: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x030e: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0310: {Symbols{".", "’", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0312: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0314: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0317: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0319: {Symbols{",", " ", "%", "-", "∞", "не число", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0322: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0326: {Symbols{",", " ", "%", "-", "∞", "чыыһыла буотах", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0328: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x032f: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0331: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x033d: {Symbols{",", " ", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0341: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0343: {Symbols{".", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0345: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"¤-", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0347: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0348: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x034f: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0351: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0353: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0357: {Symbols{",", ".", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x035f: {Symbols{",", " ", "%", "-", "∞", "epiloho", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0363: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0365: {Symbols{".", ",", "%", "-", "∞", "MaL", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x036a: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x036e: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0374: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0379: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x037c: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x037e: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0381: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0384: {Symbols{",", " ", "%", "−", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0390: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0392: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x0395: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0396: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0397: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x0399: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x039c: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x039e: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03a0: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03a3: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03a5: {Symbols{",", " ", "%", "-", "∞", "san däl", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03a7: {Symbols{".", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03ac: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{2, 2}, Grouping{0, 0}},
		0x03ae: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03b0: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03b9: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03bb: {Symbols{".", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03bf: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03c1: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03c3: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03c5: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03c6: {Symbols{".", ",", "%", "‎-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03c7: {Symbols{"٫", "٬", "%", "‎-‎", "∞", "NaN", '۰'}, Affixes{"", ""}, Affixes{"-", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x03c9: {Symbols{",", " ", "%", "-", "∞", "son emas", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03cc: {Symbols{",", " ", "%", "-", "∞", "ҳақиқий сон эмас", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03d0: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03d1: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03d5: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03d7: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03d9: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03db: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03df: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03e5: {Symbols{".", "’", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03eb: {Symbols{".", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03ed: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤", ""}, Affixes{"-¤", ""}, 1, 2, 2, Grouping{3, 2}, Grouping{0, 0}},
		0x03ef: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03f1: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03f5: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03fc: {Symbols{".", ",", "%", "-", "∞", "非數值", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x03fd: {Symbols{".", ",", "%", "-", "∞", "非数值", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0403: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " ¤"}, Affixes{"-", " ¤"}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x0405: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x040b: {Symbols{".", ",", "%", "-", "∞", "非數值", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
		0x040f: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"¤ ", ""}, Affixes{"-¤ ", ""}, 1, 2, 2, Grouping{3, 3}, Grouping{0, 0}},
	})

	// percent formats
	testNumberFormatLookup(t, PercentFormat, map[Locale]numberFormatData{
		0x0005: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x004b: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x004d: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0061: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"% ", ""}, Affixes{"% -", ""}, 1, 0, 0, Grouping{2, 2}, Grouping{0, 0}},
		0x0069: {Symbols{".", ",", "%", "-", "∞", "NaN", '০'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x006f: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0071: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 2}, Grouping{0, 0}},
		0x007c: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0085: {Symbols{".", ",", "%", "-", "∞", "NaN", '𑄶'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0088: {Symbols{".", ",", "%", "-", "∞", "Терхьаш дац", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0094: {Symbols{"٫", "٬", "٪", "‏-", "∞", "NaN", '٠'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0097: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0099: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x009d: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x009f: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00a3: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00a8: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00ab: {Symbols{".", "’", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00ae: {Symbols{".", "’", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00b4: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00b6: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00c6: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00cd: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00dd: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00df: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00e2: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x00f3: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 2}, Grouping{0, 0}},
		0x0119: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0138: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0139: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0157: {Symbols{",", ".", "%", "−", "∞", "NaN", '0'}, Affixes{"% ", ""}, Affixes{"-% ", ""}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0179: {Symbols{",", " ", "%", "−", "∞", "epäluku", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x017d: {Symbols{",", ".", "%", "−", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0180: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x018a: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x01bf: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x01c3: {Symbols{".", "’", "%", "−", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x01c7: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 2}, Grouping{0, 0}},
		0x01d8: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 2}, Grouping{0, 0}},
		0x01df: {Symbols{",", ".", "%", "−", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x01e2: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0223: {Symbols{",", ".", "%", "−", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x023d: {Symbols{",", " ", "%", "−", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x023f: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"%", ""}, Affixes{"-%", ""}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0252: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0266: {Symbols{",", " ", "%", "−", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0285: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x02b2: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x02b5: {Symbols{".", ",", "%", "-", "∞", "NaN", '०'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 2}, Grouping{0, 0}},
		0x02c6: {Symbols{",", " ", "%", "−", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x02d5: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x02e2: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 2}, Grouping{0, 0}},
		0x0302: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x030e: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{0, 0}, Grouping{0, 0}},
		0x0310: {Symbols{".", "’", "%", "−", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0312: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0314: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0319: {Symbols{",", " ", "%", "-", "∞", "не число", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x033d: {Symbols{",", " ", "%", "−", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0353: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0357: {Symbols{",", ".", "%", "−", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x035f: {Symbols{",", " ", "%", "-", "∞", "epiloho", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0384: {Symbols{",", " ", "%", "−", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0392: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 2}, Grouping{0, 0}},
		0x0395: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x0396: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x03a5: {Symbols{",", " ", "%", "-", "∞", "san däl", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x03ac: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"%", ""}, Affixes{"-%", ""}, 1, 0, 0, Grouping{2, 2}, Grouping{0, 0}},
		0x03b0: {Symbols{",", ".", "%", "-", "∞", "NaN", '0'}, Affixes{"%", ""}, Affixes{"-%", ""}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x03b9: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x03c5: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
		0x03ed: {Symbols{".", ",", "%", "-", "∞", "NaN", '0'}, Affixes{"", "%"}, Affixes{"-", "%"}, 1, 0, 0, Grouping{3, 2}, Grouping{0, 0}},
		0x0403: {Symbols{",", " ", "%", "-", "∞", "NaN", '0'}, Affixes{"", " %"}, Affixes{"-", " %"}, 1, 0, 0, Grouping{3, 3}, Grouping{0, 0}},
	})
}

func testNumberFormatLookup(t *testing.T, lookup func(Locale) NumberFormat, expected map[Locale]numberFormatData) {
	for loc, expectedData := range expected {
		nf := lookup(loc)
		data := numberFormatData{
			symbols:       nf.Symbols(),
			posAffixes:    nf.PositiveAffixes(),
			negAffixes:    nf.NegativeAffixes(),
			minIntDigits:  nf.MinIntegerDigits(),
			minFracDigits: nf.MinFractionDigits(),
			maxFracDigits: nf.MaxFractionDigits(),
			intGrouping:   nf.IntegerGrouping(),
			fracGrouping:  nf.FractionGrouping(),
		}
		if !reflect.DeepEqual(data, expectedData) {
			t.Fatalf("unexpected number format for %s", loc.String())
		}
	}
}

func TestAffix(t *testing.T) {
	const s affix = "\x02\x04aabb"

	expected := [2]string{"aa", "bb"}
	get := [2]func() string{s.prefix, s.suffix}

	for i := 0; i < 2; i++ {
		if str := get[i](); str != expected[i] {
			t.Errorf("unexpected affix at %d: %s", i, str)
		}
	}
}

func TestAffixLookup(t *testing.T) {
	const lookup affixLookup = "\x04\x07\x0a\x10foobarfoobar"

	if s := lookup.affix(1); s != "foo" {
		t.Errorf("unexpected affix for id 1: %q", s)
	}
	if s := lookup.affix(2); s != "bar" {
		t.Errorf("unexpected affix for id 2: %q", s)
	}
	if s := lookup.affix(3); s != "foobar" {
		t.Errorf("unexpected affix for id 3: %q", s)
	}

	if s := lookup.affix(0); s != "\x00\x00" {
		t.Errorf("unexpected symbols for id 0: %q", s)
	}
}

func TestPattern(t *testing.T) {
	const pattern pattern = 0x102345678

	if id := pattern.posAffixID(); id != 1 {
		t.Errorf("unexpected positive affix id: %d", id)
	}
	if id := pattern.negAffixID(); id != 2 {
		t.Errorf("unexpected negative affix id: %d", id)
	}
	if n := pattern.minIntDigits(); n != 3 {
		t.Errorf("unexpected minimum integer digits: %d", n)
	}
	if n := pattern.minFracDigits(); n != 4 {
		t.Errorf("unexpected minimum fraction digits: %d", n)
	}
	if n := pattern.maxFracDigits(); n != 5 {
		t.Errorf("unexpected minimum fraction digits: %d", n)
	}
	if m, n := pattern.intGrouping(); m != 6 || n != 7 {
		t.Errorf("unexpected integer grouping: (%d, %d)", m, n)
	}
	if n := pattern.fracGrouping(); n != 8 {
		t.Errorf("unexpected fraction grouping: %d", n)
	}
}

func TestPatternLookup(t *testing.T) {
	lookup := patternLookup{1, 2, 3}

	for i := 0; i < len(lookup); i++ {
		if p := lookup.pattern(patternID(i + 1)); p != lookup[i] {
			t.Errorf("unexpected pattern for id %d: %#x", i+1, p)
		}
	}

	if p := lookup.pattern(0); p != 0 {
		t.Errorf("unexpected pattern for id 0: %#x", p)
	}
	if p := lookup.pattern(patternID(len(lookup) + 1)); p != 0 {
		t.Errorf("unexpected pattern for id %d: %#x", len(lookup)+1, p)
	}
}

func TestSymbols(t *testing.T) {
	const s symbols = "\x02\x04\x06\x08\x0a\x0c\x0e\x10aabbccddeeffgghh"

	expected := [8]string{"aa", "bb", "cc", "dd", "ee", "ff", "gg", "hh"}
	get := [8]func() string{s.decimal, s.group, s.percent, s.minus, s.inf, s.nan, s.currDecimal, s.currGroup}

	for i := 0; i < 8; i++ {
		if str := get[i](); str != expected[i] {
			t.Errorf("unexpected symbols at %d: %s", i, str)
		}
	}
}

func TestSymbolsLookup(t *testing.T) {
	const lookup symbolsLookup = "\x00\x08\x00\x0b\x00\x0e\x00\x14foobarfoobar"

	if s := lookup.symbols(1); s != "foo" {
		t.Errorf("unexpected symbols for id 1: %q", s)
	}
	if s := lookup.symbols(2); s != "bar" {
		t.Errorf("unexpected symbols for id 2: %q", s)
	}
	if s := lookup.symbols(3); s != "foobar" {
		t.Errorf("unexpected symbols for id 3: %q", s)
	}

	if s := lookup.symbols(0); s != "\x00\x00\x00\x00\x00\x00\x00\x00" {
		t.Errorf("unexpected symbols for id 0: %q", s)
	}
}

func TestZeroLookup(t *testing.T) {
	const lookup zeroLookup = "0az"

	if r := lookup.zero(0); r != utf8.RuneError {
		t.Errorf("unexpected zero for id 0: %U", r)
	}
	if r := lookup.zero(1); r != '0' {
		t.Errorf("unexpected zero for id 1: %U", r)
	}
	if r := lookup.zero(2); r != 'a' {
		t.Errorf("unexpected zero for id 2: %U", r)
	}
	if r := lookup.zero(3); r != 'z' {
		t.Errorf("unexpected zero for id 3: %U", r)
	}
	if r := lookup.zero(4); r != utf8.RuneError {
		t.Errorf("unexpected zero for id 4: %U", r)
	}
}

func TestNumbers(t *testing.T) {
	const numbers numbers = 0x10203

	if id := numbers.patternID(); id != 1 {
		t.Errorf("unexpected pattern id: %d", id)
	}
	if id := numbers.symbolsID(); id != 2 {
		t.Errorf("unexpected symbols id: %d", id)
	}
	if id := numbers.zeroID(); id != 3 {
		t.Errorf("unexpected zero id: %d", id)
	}
}
